#spring.application.name=lovemyself

server:
  port: 8080  # ?? ??, ??? ?? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: PSC
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.psc.loovemyself.dto # DTO ?? VO ?? ?? ??
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.psc.lovemyself: debug  # ??? ?? ??


